Repository Sparta-newsfeed-team/Sparta-Newsfeed-Project, pull requests merged in 2025-08, with the labels that each got.

#45 Refactor: post code convention
  src/main/java/com/example/newsfeedproject/post/controller/PostController.java
  src/main/java/com/example/newsfeedproject/post/dto/PostListResponse.java
  src/main/java/com/example/newsfeedproject/post/dto/PostResponse.java
  src/main/java/com/example/newsfeedproject/post/entity/Post.java
  src/main/java/com/example/newsfeedproject/post/service/PostService.java
Labels: ♻️ Refactoring

#50 refactor:auth convention fix
  src/main/java/com/example/newsfeedproject/auth/controller/AuthController.java
  src/main/java/com/example/newsfeedproject/auth/service/AuthService.java
Labels: ♻️ Refactoring

#53 feat: 팔로우 기반 뉴스피드 조회 기능 구현
  src/main/java/com/example/newsfeedproject/post/controller/PostController.java
  src/main/java/com/example/newsfeedproject/post/repository/PostRepository.java
  src/main/java/com/example/newsfeedproject/post/service/PostService.java
Labels: ⭐️ Feature

#56 fix: post response 수정 및 postuserresponse 생성
  src/main/java/com/example/newsfeedproject/post/dto/PostResponse.java
  src/main/java/com/example/newsfeedproject/user/dto/PostUserResponse.java
Labels: 😡 Bug Fix

#61 전역 @Valid 예외 처리 기능 추가
  src/main/java/com/example/newsfeedproject/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeedproject/common/exception/GlobalExceptionHandler.java
Labels: ⭐️ Feature

#72 UpdateUserInfo 입력값 검증 로직 리팩토링
  src/main/java/com/example/newsfeedproject/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeedproject/domain/user/dto/UpdateUserInfoRequest.java
  src/main/java/com/example/newsfeedproject/domain/user/entity/User.java
  src/main/java/com/example/newsfeedproject/domain/user/service/UserService.java
Labels: ♻️ Refactoring

#74 fix: like compile
  src/main/java/com/example/newsfeedproject/domain/like/entity/Like.java
  src/main/java/com/example/newsfeedproject/domain/like/repository/LikeRepository.java
  src/main/java/com/example/newsfeedproject/domain/like/service/LikeService.java
Labels: 😡 Bug Fix

#80 User DTO 필드 누락 및 검증 로직 수정
  src/main/java/com/example/newsfeedproject/common/annotation/ValidPassword.java
  src/main/java/com/example/newsfeedproject/domain/auth/service/AuthService.java
  src/main/java/com/example/newsfeedproject/domain/like/dto/LikeListResponse.java
  src/main/java/com/example/newsfeedproject/domain/post/dto/PostResponse.java
  src/main/java/com/example/newsfeedproject/domain/user/dto/AuthorResponse.java
  src/main/java/com/example/newsfeedproject/domain/user/dto/UpdateUserInfoRequest.java
  src/main/java/com/example/newsfeedproject/domain/user/dto/UserResponse.java
Labels: ♻️ Refactoring, 😡 Bug Fix
